### PR TITLE
CI: Add Apk Upload && Add md5 check and retry for hidden-api android-30.jar

### PR DESCRIPTION
**Pull request by lelemka0**
supplement: Fix an error in NativeHook && Update Optimization

### CODE REVIEW

**Comment by lelemka0** [comment]
Supplement 2: Try to auto sign apks after build when secrets.KEY_STORE is set.
(Need to set KEY_STORE, KEY_STORE_PASSWORD, ALIAS, KEY_PASSWORD in repo's secrets.)
(keystore file need to be converted to Base64)
When keystore is not set, unsigned apks will be uploaded.

**Comment by Dr-TSNG** [comment]
It's tricky that I don't know how to convert keystore file to Base64. I have a .jks file, how to deal with it?

**Comment by Dr-TSNG** [comment]
OK, I made it

**Comment by omidbarzegaran** [comment]
غمنتنهمنن

**Pull request merged**
