### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Comment by Dr-TSNG** [comment]
Some strings changed in this file, please check

**Comment by xerta555** [comment]
> 
> 
> Some strings changed in this file, please check
I just updated the file, but the automated compilation is failing again...really buggy this thing ^^

**Comment by Dr-TSNG** [comment]
It's normal that it fails. I have not fixed it yet 😄

**Comment by Dr-TSNG** [comment]
Anyway no need to add those "translatable=false" items

**Comment by xerta555** [comment]
> 
> 
> It's normal that it fails. I have not fixed it yet 😄

It all makes sense haha ^^

**Comment by xerta555** [comment]
> translatable=false

I don't see no translatable sentence in this file

**Pull request closed without merging**
