### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by xerta555**

### CODE REVIEW

**Comment by Dr-TSNG** [comment]
Compilation action check failed, there are some problems existing

**Comment by xerta555** [comment]
> 
> 
> Compilation action check failed, there are some problems existing

> Execution failed for task ':app:dexTailDebug'.
> dex not found: we only support 3.6.x, 4.0.x and 4.1.x

Issue do not come from translation file(s) apparently.

**Comment by Dr-TSNG** [comment]
/home/runner/work/Hide-My-Applist/Hide-My-Applist/app/src/main/res/values-fr/strings_template.xml:32:4: Failed to flatten XML for resource 'template_add_maps_rules' with error: Invalid unicode escape sequence in string
"{str}"
/home/runner/work/Hide-My-Applist/Hide-My-Applist/app/src/main/res/values-fr/strings_template.xml:32:4: string/template_add_maps_rules does not contain a valid string resource.

**Comment by xerta555** [comment]
image

It's all that i see

**Comment by Dr-TSNG** [comment]
If you encounter "dex not found", just re-run action. It is a random bug lol

**Comment by xerta555** [comment]
> 
> 
> If you encounter "dex not found", just re-run action. It is a random bug lol

Ok ouf :P

**Comment by cracky5322** [comment]
@xerta555 💬 New comment on Hide-My-Applist#86 Update French translation
by @xerta555

>  
>  
> If you encounter "dex not found", just re-run action. It is a random bug lol 
 
Ok ouf :P 

Reply to this message to post a comment on GitHub.

**Pull request merged**
